version: '3.3'

services:
  bd_he:
    container_name: foodgram-db
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - foodgram_pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=foodgram1489
      - POSTGRES_USER=foodgram229
      - POSTGRES_PASSWORD=foodgram227
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foodgram229 -d foodgram1489"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../
      dockerfile: backend/Dockerfile
    container_name: kirill-back
    ports:
      - "8000:8000"
    env_file: ../.env
    volumes:
      - ../backend:/app/backend
      - ../data:/app/data:ro 
      - static_volume:/app/backend/static
      - media_volume:/app/backend/media
    depends_on:
      bd_he:
        condition: service_healthy

volumes:
  foodgram_pg_data:
  static_volume:
  media_volume:
